name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs: 
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ububtu-lastest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses:  actions/chekout@v2
      # sets up .NET Core SDK 7.x
      - name: Setup .Net Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with: 
          dotnet-version: 7.x
      #publishes Blazor project to release-folder
      - name: Publish .NET Core Project
        run: dotnet publish Portfolio2.csproj -c Release -o release --nologo
        # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
        # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit wwwroot to GitHub Pages
        uses: Galboss/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwroot
